

UPDATE autor SET telefone ='11999-7777' WHERE id =1;

----- ATENÇÂO EM COLOCAR A CONDIÇÃO WHERE PARA ATUALIZAR SOMENTE O CAMPO DESEJADO, SEM WHERE ELE ATUALIZA TODOS OS VALORES DO CAMPO DA TABELA.

Update editora
set cidade = "Piracicaba" WHERE id =3;
